In [1]:
from importlib_metadata import version
version("torch")

'2.4.1+cu118'

In [2]:
version("tiktoken")

'0.9.0'

In [3]:
with open('the_verdict.txt', "r", encoding='utf-8') as f:
    raw_text = f.read()


In [4]:
raw_text

'I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a rich widow, and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)\n\n"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it\'s going to send the value of my picture \'way up; but I don\'t think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing\'s lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me before Gisburn\'s "Moon-dancers" to say, with tears in her eyes: "We shall not look upon its like again"?\n\nWell!--even 

In [27]:
import re
text = 'Hello, world. Is this-- a test'
text = re.split(r'(\s)', text)
text

['Hello,', ' ', 'world.', ' ', 'Is', ' ', 'this--', ' ', 'a', ' ', 'test']

In [28]:
text = 'Hello, world. Is this-- a test'

text = re.split(r'([,.]|\s)', text)
text


['Hello',
 ',',
 '',
 ' ',
 'world',
 '.',
 '',
 ' ',
 'Is',
 ' ',
 'this--',
 ' ',
 'a',
 ' ',
 'test']

In [29]:
result = [items for items in text if items.split()]
result

['Hello', ',', 'world', '.', 'Is', 'this--', 'a', 'test']

In [30]:
raw_text = re.split(r'([[,.:;?_!"()\']|--|\s)', raw_text)
raw_text = [item for item in raw_text if item.split()]
raw_text

TypeError: expected string or bytes-like object, got 'list'

In [ ]:
preprocessed = raw_text

In [ ]:
print(len(preprocessed))

4690


In [ ]:
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)
print(vocab_size)

1130


In [36]:
vocab = {token:integer for integer, token in enumerate(all_words)}

In [37]:
vocab

{'!': 0,
 '"': 1,
 "'": 2,
 '(': 3,
 ')': 4,
 ',': 5,
 '--': 6,
 '.': 7,
 ':': 8,
 ';': 9,
 '?': 10,
 'A': 11,
 'Ah': 12,
 'Among': 13,
 'And': 14,
 'Are': 15,
 'Arrt': 16,
 'As': 17,
 'At': 18,
 'Be': 19,
 'Begin': 20,
 'Burlington': 21,
 'But': 22,
 'By': 23,
 'Carlo': 24,
 'Chicago': 25,
 'Claude': 26,
 'Come': 27,
 'Croft': 28,
 'Destroyed': 29,
 'Devonshire': 30,
 'Don': 31,
 'Dubarry': 32,
 'Emperors': 33,
 'Florence': 34,
 'For': 35,
 'Gallery': 36,
 'Gideon': 37,
 'Gisburn': 38,
 'Gisburns': 39,
 'Grafton': 40,
 'Greek': 41,
 'Grindle': 42,
 'Grindles': 43,
 'HAD': 44,
 'Had': 45,
 'Hang': 46,
 'Has': 47,
 'He': 48,
 'Her': 49,
 'Hermia': 50,
 'His': 51,
 'How': 52,
 'I': 53,
 'If': 54,
 'In': 55,
 'It': 56,
 'Jack': 57,
 'Jove': 58,
 'Just': 59,
 'Lord': 60,
 'Made': 61,
 'Miss': 62,
 'Money': 63,
 'Monte': 64,
 'Moon-dancers': 65,
 'Mr': 66,
 'Mrs': 67,
 'My': 68,
 'Never': 69,
 'No': 70,
 'Now': 71,
 'Nutley': 72,
 'Of': 73,
 'Oh': 74,
 'On': 75,
 'Once': 76,
 'Only': 77,
 '

In [35]:
vocab

{0: '!',
 1: '"',
 2: "'",
 3: '(',
 4: ')',
 5: ',',
 6: '--',
 7: '.',
 8: ':',
 9: ';',
 10: '?',
 11: 'A',
 12: 'Ah',
 13: 'Among',
 14: 'And',
 15: 'Are',
 16: 'Arrt',
 17: 'As',
 18: 'At',
 19: 'Be',
 20: 'Begin',
 21: 'Burlington',
 22: 'But',
 23: 'By',
 24: 'Carlo',
 25: 'Chicago',
 26: 'Claude',
 27: 'Come',
 28: 'Croft',
 29: 'Destroyed',
 30: 'Devonshire',
 31: 'Don',
 32: 'Dubarry',
 33: 'Emperors',
 34: 'Florence',
 35: 'For',
 36: 'Gallery',
 37: 'Gideon',
 38: 'Gisburn',
 39: 'Gisburns',
 40: 'Grafton',
 41: 'Greek',
 42: 'Grindle',
 43: 'Grindles',
 44: 'HAD',
 45: 'Had',
 46: 'Hang',
 47: 'Has',
 48: 'He',
 49: 'Her',
 50: 'Hermia',
 51: 'His',
 52: 'How',
 53: 'I',
 54: 'If',
 55: 'In',
 56: 'It',
 57: 'Jack',
 58: 'Jove',
 59: 'Just',
 60: 'Lord',
 61: 'Made',
 62: 'Miss',
 63: 'Money',
 64: 'Monte',
 65: 'Moon-dancers',
 66: 'Mr',
 67: 'Mrs',
 68: 'My',
 69: 'Never',
 70: 'No',
 71: 'Now',
 72: 'Nutley',
 73: 'Of',
 74: 'Oh',
 75: 'On',
 76: 'Once',
 77: 'Only',
 7

In [38]:
for i, token in enumerate(vocab.items()):
    print(token)
    if i>50:
        break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)
('His', 51)


In [42]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s, i in vocab.items()}
    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text


In [47]:
strs = {i:s for s, i in vocab.items()}
strs

{0: '!',
 1: '"',
 2: "'",
 3: '(',
 4: ')',
 5: ',',
 6: '--',
 7: '.',
 8: ':',
 9: ';',
 10: '?',
 11: 'A',
 12: 'Ah',
 13: 'Among',
 14: 'And',
 15: 'Are',
 16: 'Arrt',
 17: 'As',
 18: 'At',
 19: 'Be',
 20: 'Begin',
 21: 'Burlington',
 22: 'But',
 23: 'By',
 24: 'Carlo',
 25: 'Chicago',
 26: 'Claude',
 27: 'Come',
 28: 'Croft',
 29: 'Destroyed',
 30: 'Devonshire',
 31: 'Don',
 32: 'Dubarry',
 33: 'Emperors',
 34: 'Florence',
 35: 'For',
 36: 'Gallery',
 37: 'Gideon',
 38: 'Gisburn',
 39: 'Gisburns',
 40: 'Grafton',
 41: 'Greek',
 42: 'Grindle',
 43: 'Grindles',
 44: 'HAD',
 45: 'Had',
 46: 'Hang',
 47: 'Has',
 48: 'He',
 49: 'Her',
 50: 'Hermia',
 51: 'His',
 52: 'How',
 53: 'I',
 54: 'If',
 55: 'In',
 56: 'It',
 57: 'Jack',
 58: 'Jove',
 59: 'Just',
 60: 'Lord',
 61: 'Made',
 62: 'Miss',
 63: 'Money',
 64: 'Monte',
 65: 'Moon-dancers',
 66: 'Mr',
 67: 'Mrs',
 68: 'My',
 69: 'Never',
 70: 'No',
 71: 'Now',
 72: 'Nutley',
 73: 'Of',
 74: 'Oh',
 75: 'On',
 76: 'Once',
 77: 'Only',
 7

In [44]:
tokenizer= SimpleTokenizerV1(vocab)
text = """"It's the last he painted, you know," 
           Mrs. Gisburn said with pardonable pride."""
tokens = tokenizer.encode(text)
tokens


[1,
 56,
 2,
 850,
 988,
 602,
 533,
 746,
 5,
 1126,
 596,
 5,
 1,
 67,
 7,
 38,
 851,
 1108,
 754,
 793,
 7]

In [45]:
text = tokenizer.decode(tokens)

In [46]:
text

'" It\' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.'

In [57]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

In [59]:
vocab = {token:integer for integer, token in enumerate(all_tokens)}
len(vocab.items())

1132

In [60]:
for i, item in enumerate(list(vocab.items()) [5:]):
    print(item)


(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)
('His', 51)
('How', 52)
('I', 53)
('If', 54)
('In', 55)
('It', 56)
('Jack', 57)
('Jove', 58)
('Just', 59)
('Lord', 60)
('Made', 61)
('Miss', 62)
('Money', 63)
('Monte', 64)
('Moon-dancers', 65)
('Mr', 66)
('Mrs', 67)
('My', 68)
('Never', 69)
('No', 70)
('Now', 71)
('Nutley', 72)
('Of', 73)
('Oh', 74)
('On', 75)
('Once', 76)
('Only', 77)
('Or', 78)
('Perhaps', 79)
('Poor', 80)
('Profe

In [61]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s, i in vocab.items()}
    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        preprocessed = [
            item if item in self.str_to_int
            else "<|unk|>" for item in preprocessed
        ]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text


In [63]:
tokenizer = SimpleTokenizerV2(vocab)
text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."
text = "<|endoftext|>".join((text1, text2))
tokenizer.encode(text)

[1131, 5, 355, 1126, 628, 975, 10, 1131, 988, 956, 984, 722, 988, 1131, 7]

In [64]:
tokenizer.decode(tokenizer.encode(text))

'<|unk|>, do you like tea? <|unk|> the sunlit terraces of the <|unk|>.'

In [1]:
import tiktoken

tokenizer = tiktoken.get_encoding('gpt2')

In [2]:
text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
     "of someunknownPlace."
)
integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})

In [4]:
print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


In [5]:
strings = tokenizer.decode(integers)
print(strings)


Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.


In [6]:
with open('the_verdict.txt', 'r', encoding='utf-8') as f:
    raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

5145


In [9]:
enc_sample = enc_text[50:]

chunk_size = 4

x = enc_sample[:chunk_size]
y = enc_sample[1:chunk_size+1]
print(f"x: {x}")
print(f"y:   {y}")

x: [290, 4920, 2241, 287]
y:   [4920, 2241, 287, 257]


In [11]:
for i in range(1, chunk_size+1):
    context = enc_sample[:i]
    desire = enc_sample[i]
    print(context, "----->", desire)

[290] -----> 4920
[290, 4920] -----> 2241
[290, 4920, 2241] -----> 287
[290, 4920, 2241, 287] -----> 257


In [13]:
for i in range(1, chunk_size+1):
    context = enc_sample[:i]
    desire = enc_sample[i]
    print(tokenizer.decode(context), "----->", tokenizer.decode([desire]))

 and ----->  established
 and established ----->  himself
 and established himself ----->  in
 and established himself in ----->  a


In [14]:
import torch

In [85]:
from torch.utils.data import Dataset, DataLoader
class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunks = token_ids[i:i+max_length]
            target_chunks = token_ids[i+1: max_length+i+1]
            self.input_ids.append(torch.tensor(input_chunks))
            self.target_ids.append(torch.tensor(target_chunks))

    def __len__(self):
        return len(self.input_ids)
    
    def __getitem__(self, index):
        return self.input_ids[index],self.target_ids[index]

        

In [86]:
def create_loader_v1(txt, batch_size = 4, max_length = 256, stride = 128, shuffle = True, drop_last = True,  num_workers = 0):
    
    token = tiktoken.get_encoding("gpt2")

    datasetv1 = GPTDatasetV1(txt, token, max_length, stride)

    dataloader = DataLoader(
        datasetv1,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    
    )
    return dataloader

In [87]:
dataloader = create_loader_v1(raw_text, batch_size=2, max_length=8, stride=2, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)


Inputs:
 tensor([[   40,   367,  2885,  1464,  1807,  3619,   402,   271],
        [ 2885,  1464,  1807,  3619,   402,   271, 10899,  2138]])

Targets:
 tensor([[  367,  2885,  1464,  1807,  3619,   402,   271, 10899],
        [ 1464,  1807,  3619,   402,   271, 10899,  2138,   257]])


In [88]:
with open("the_verdict.txt", "r", encoding='utf-8') as f:
    raw_text = f.read()

In [89]:
# Byte pair encoder
vocab_size = 50257
output_dim = 256

token_embedding_layers = torch.nn.Embedding(vocab_size, output_dim)

In [90]:
max_length = 4
dataloader = create_loader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)

data_iter = iter(dataloader)

inputs, targets = next(data_iter)

In [91]:
print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Inputs shape:
 torch.Size([8, 4])


In [92]:
token_embeddings = token_embedding_layers(inputs)

In [93]:
print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [94]:
print(token_embeddings)

tensor([[[ 1.0295e+00, -1.2536e+00, -7.4715e-01,  ...,  9.0878e-01,
           1.3041e-03,  1.1340e+00],
         [ 7.4585e-01,  6.6693e-01, -8.3670e-01,  ..., -4.4377e-01,
          -1.8527e+00,  4.3747e-01],
         [ 6.3397e-01,  1.1012e+00, -1.0798e+00,  ..., -1.0965e+00,
          -2.9768e-01, -2.4721e-01],
         [-1.8041e+00,  5.8654e-02,  6.9493e-01,  ..., -3.0506e-01,
          -1.6875e+00,  2.5369e-01]],

        [[ 6.8525e-01, -4.2650e-01,  9.1337e-01,  ..., -8.4472e-01,
           9.0939e-01,  1.5498e+00],
         [-9.3896e-01, -1.7391e-01, -1.0585e+00,  ...,  1.0583e+00,
           2.5396e-01, -3.1910e-02],
         [-4.5087e-02,  2.6669e-02,  9.3086e-01,  ...,  1.2750e+00,
          -3.1178e-01, -1.5746e+00],
         [-7.2889e-01,  5.0940e-01, -2.0718e-01,  ..., -4.1859e-01,
          -1.6951e+00,  1.5881e+00]],

        [[-1.1985e+00,  6.0740e-01, -1.0566e+00,  ..., -2.4523e-01,
          -7.0118e-01, -1.3788e+00],
         [ 1.3548e+00,  8.5480e-01, -4.1175e-01,  .

In [101]:
context_len = 1024
pos_embedding_layers = torch.nn.Embedding(context_len, output_dim)

In [102]:
print(pos_embedding_layers.weight)

Parameter containing:
tensor([[ 0.6630,  0.6723,  0.7993,  ..., -0.3498,  1.4639,  1.4116],
        [ 0.5505,  1.2767,  0.2888,  ...,  1.9726, -1.9062,  1.1854],
        [ 0.8805,  2.1543,  0.2571,  ..., -1.1491, -0.6262,  1.1748],
        ...,
        [-1.2676, -0.9360,  0.3945,  ...,  0.0412,  0.4506,  0.3930],
        [-0.1525, -1.0461,  0.1005,  ..., -0.1487, -0.6463, -0.7225],
        [-0.3621,  0.2536,  0.7491,  ...,  0.0123,  0.8700,  0.0371]],
       requires_grad=True)


In [103]:
pos_embedding_layers

Embedding(1024, 256)

In [104]:
pos_embeddings = pos_embedding_layers(torch.arange(max_length))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [105]:
print(pos_embeddings)

tensor([[ 0.6630,  0.6723,  0.7993,  ..., -0.3498,  1.4639,  1.4116],
        [ 0.5505,  1.2767,  0.2888,  ...,  1.9726, -1.9062,  1.1854],
        [ 0.8805,  2.1543,  0.2571,  ..., -1.1491, -0.6262,  1.1748],
        [-0.9793,  0.6244, -1.6371,  ...,  0.7344,  2.3656,  0.3812]],
       grad_fn=<EmbeddingBackward0>)


In [106]:
# to create embeddings used in LLM, we simply add token embeddings and positional embeddings
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])


In [107]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [108]:
query = inputs[1]

In [109]:
query

tensor([0.5500, 0.8700, 0.6600])

In [110]:
attn_weights = torch.empty(inputs.shape[0])

In [111]:
for i, x_i in enumerate(inputs):
    attn_weights[i] = torch.dot(x_i, query)

print(attn_weights)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [112]:
res = 0
for i, elem in enumerate(inputs[0]):
    res += elem * query[i]

print(res)

tensor(0.9544)


In [113]:
print(torch.dot(inputs[0], query))

tensor(0.9544)


In [114]:
attn_weights_tmp = attn_weights / attn_weights.sum()

In [115]:
print(attn_weights_tmp)

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])


In [116]:
print(attn_weights_tmp.sum())

tensor(1.0000)


In [117]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

attn_weights_tmp_2= softmax_naive(attn_weights)

In [118]:
print("Attention weights:", attn_weights_tmp_2)
print("Sum:", attn_weights_tmp_2.sum())

Attention weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: tensor(1.)


In [119]:
attn_weights_2 = torch.softmax(attn_weights, dim=0)
print("Attention weights: ", attn_weights_2)
print("SUM: ", attn_weights_2.sum())


Attention weights:  tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
SUM:  tensor(1.)


In [120]:
query = inputs[i]

context_vec2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    context_vec2 += attn_weights_2[i]*x_i

print(context_vec2)

tensor([0.4419, 0.6515, 0.5683])


In [121]:
attn_scores = inputs @ inputs.T
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [131]:
attn_weights = torch.softmax(attn_scores, dim = 1)
print(attn_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [132]:
print("All rows sum: ", attn_weights.sum(dim=1))

All rows sum:  tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [133]:
context_vec_2 = attn_weights @ inputs
print(context_vec_2)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


In [134]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

In [135]:
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad= False)
W_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)


In [136]:
query_2 = x_2 @ W_query
value_2 = x_2 @ W_value
key_2 = x_2 @ W_key

In [137]:
print(query_2)

tensor([0.9501, 1.0360])


In [138]:
keys = inputs @ W_key
values = inputs @ W_value
print("Keys.shape", keys.shape)
print("values.shape", values.shape)

Keys.shape torch.Size([6, 2])
values.shape torch.Size([6, 2])


In [139]:
attn_scores_2 = query_2 @ keys.T
print(attn_scores_2)

tensor([1.6482, 2.5138, 2.4685, 1.4463, 0.9582, 1.9732])


In [141]:
d_k = keys.shape[1]
attn_weights_2 = torch.softmax(attn_scores_2 / d_k ** 0.5, dim= -1)
print(attn_weights_2)

tensor([0.1357, 0.2502, 0.2424, 0.1176, 0.0833, 0.1707])


In [142]:
context_vec_2 = attn_weights_2 @ values
print(context_vec_2)

tensor([0.3982, 0.9109])


In [145]:
import torch.nn as nn 
class SelfAttention_v1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_key = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
    def forward(self, x):
        keys = x @ self.W_key
        queries = x@self.W_query
        values = x@self.W_value
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1] ** 0.5, dim=1)
        context_vec = attn_weights @ values
        return context_vec
    
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in, d_out)
print(sa_v1(inputs))

tensor([[0.3508, 0.8808],
        [0.3539, 0.8896],
        [0.3535, 0.8885],
        [0.3446, 0.8637],
        [0.3401, 0.8510],
        [0.3495, 0.8774]], grad_fn=<MmBackward0>)
